### ISSUE TITLE
[dev] Install RailsDB to easily check what's in the db

### ISSUE THREAD

**Issue by chikamichi** [thomasjacobjr/SwimClub#8]
There is this [RailsDB](https://github.com/igorkasyanchuk/rails_db) project which you could [install in the development group](https://github.com/igorkasyanchuk/rails_db#install). It's quite handy as it lets you inspect your database's content.

It cannot be turned into a proper administration panel and just exposes all the gory details about the db, that's why you're going to use [ActiveAdmin](http://activeadmin.info/) to build your client's /admin area; but during development, it's a nice tool to have up and running.

**Comment by thomasjacobjr** [comment]
Installed!
